-- MySQL Script generated by MySQL Workbench
-- Mon Mar 10 10:07:44 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sport
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sport
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sport` DEFAULT CHARACTER SET utf8 ;
USE `sport` ;

-- -----------------------------------------------------
-- Table `sport`.`medlem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sport`.`medlem` (
  `m_nr` INT NOT NULL AUTO_INCREMENT,
  `fornavn` VARCHAR(30) NULL,
  `etternavn` VARCHAR(50) NULL,
  `adresse` VARCHAR(70) NULL,
  `postnr` VARCHAR(4) NULL,
  `poststed` VARCHAR(100) NULL,
  `fodt` DATE NULL,
  `telefon` VARCHAR(12) NULL,
  `mail` VARCHAR(100) NULL,
  `betalt` VARCHAR(3) NULL COMMENT 'Betalt kontingent (ja eller nei)',
  PRIMARY KEY (`m_nr`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
