-- MySQL Script generated by MySQL Workbench
-- Tue Feb  4 11:06:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Biler
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Biler
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Biler` DEFAULT CHARACTER SET utf8 ;
USE `Biler` ;

-- -----------------------------------------------------
-- Table `Biler`.`Biler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Biler`.`Biler` (
  `Regnr` VARCHAR(7) NOT NULL,
  `Merke` VARCHAR(20) NOT NULL,
  `Type` VARCHAR(25) NOT NULL,
  `Farge` VARCHAR(25) NOT NULL,
  `Aarsmodell` VARCHAR(4) NOT NULL,
  PRIMARY KEY (`Regnr`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
