-- MySQL Script generated by MySQL Workbench
-- Sun Feb  9 21:25:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biler-2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biler-2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biler-2` DEFAULT CHARACTER SET utf8 ;
USE `biler-2` ;

-- -----------------------------------------------------
-- Table `biler-2`.`Biler`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biler-2`.`Biler` (
  `Regnr` VARCHAR(7) NOT NULL,
  `Merke` VARCHAR(45) NULL,
  `Type` VARCHAR(45) NULL,
  `Farge` VARCHAR(45) NULL,
  `Aar` VARCHAR(4) NULL,
  PRIMARY KEY (`Regnr`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
